### ISSUE TITLE
Hi, is there a way to make news item slug editable in admin?

### ISSUE THREAD

**Issue by aientrp** [neon-jungle/wagtailnews#26]

**Comment by seb-b** [comment]
Hi, no not at the moment it's generated based on the primary key + title. You could in theory add your own `SlugField` to the news item and then override the `get_slug` method. Your urls will end up looking like `year/month/day/pk-yourslug/`

```python
class NewsItem(AbstractNewsItem):
    # other fields
    slug = models.SlugField(max_length=255)
    
    def get_slug(self):
        return self.slug
```

Or if you want shorter urls you could write a new `@route` on the news index that finds the news item based on the slug:

```python
@newsindex
class NewsIndex(NewsIndexMixin, Page)
     # rest of the model
     @route(r'^(?P<slug>.*)/$', name='slug')
     def v_slug(self, request, slug):
         newsitem = get_object_or_404(self.get_newsitems_for_display(), slug=slug)
         return newsitem.serve(request)
```

**Comment by aientrp** [comment]
I'll try, thanks!👍
